# Generated by Django 5.0.6 on 2024-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_class_11th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_class_12th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dropper',
            field=models.BooleanField(default=False),
        ),
    ]
